version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: poc-rabbitmq
    ports:
      - "5672:5672"   # puerto AMQP para Spring Boot
      - "15672:15672" # panel de administracion web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
