# Generated by Django 4.2.20 on 2026-04-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'archivo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('lenguaje', models.CharField(choices=[('CPP', 'C++'), ('PYTHON', 'Python'), ('TYPESCRIPT', 'TypeScript')], max_length=10)),
            ],
            options={
                'verbose_name': 'proyecto',
                'ordering': ['-fechaCreacion'],
            },
        ),
    ]
