# Generated by Django 4.2.20 on 2026-05-18 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fechaCreacion')),
                ('lenguaje', models.CharField(choices=[('CPP', 'C++'), ('PYTHON', 'Python'), ('TYPESCRIPT', 'TypeScript')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proyecto',
                'db_table': 'proyectos',
                'ordering': ['-fecha_creacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fechaCreacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='fechaActualizacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='projects.proyecto')),
            ],
            options={
                'verbose_name': 'archivo',
                'db_table': 'archivos',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=512)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_sessions', to='projects.proyecto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collab_sessions',
                'ordering': ['-last_seen'],
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='archivo',
            unique_together={('proyecto', 'nombre')},
        ),
    ]
