# Generated by Django 4.2.20 on 2026-05-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proyecto_colaboradores',
                'ordering': ['fecha_agregado'],
                'managed': False,
            },
        ),
    ]
