# Generated by Django 4.2.20 on 2026-05-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_proyectocolaborador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectocolaborador',
            options={'managed': True, 'ordering': ['fecha_agregado']},
        ),
    ]
