events {}

http {
    upstream backend {
        server evaluacion1:8081;
        server evaluacion2:8082;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}
